export const ProductConstant = {
    description: "Комментарии (доп. описание)",
    photo1: "Фото 1",
    colour: "Цвет",
    productMaterial: "Материал изделия",
    sizeChart: "Размерная сетка",
    repeatedDimensions: "Повторные размеры",
    steamInBox: "Пар в ящике",
    liningMaterial: "Материал подкладки",
    outsoleMaterial: "Материал подошвы",
    country: "Страна",
    heelHeight: "Высота каблука, см",
    platformHeight: "Высота платформы",
    picturedSize: "Размер (на фото)",
    purchasePrice: "Цена закупки",
    sellingPrice: "Цена продажи",
    season: "Сезон",
    shootingDate: "Дата съемки",
    purchaseCurrency: "Валюта закупки",
    saleCurrency: "Валюта продажи",
    floor: "Пол",
    type: "Тип",
    oldPurchasePrice: "Старая цена закупки",
    oldSellingPrice: "Старая цена продажи",
    insoleMaterial: "Материал стельки",
    videoReview: "Видеообзор",
}